### PR TITLE
Fixes Warning Log

### PR DESCRIPTION
**Pull request by donavanbecker**
@moritzmhmk, This was posted on [reddit](https://www.reddit.com/r/homebridge/comments/gnf1jd/was_checking_my_logs_and_saw_an_interesting_log/).

```
[rpi-camera] Initializing rpi-camera platform...
One of your plugins incorrectly registered an external accessory using the platform name (rpi-camera) and not the plugin identifier. Please report this to the developer!
```

### CODE REVIEW

**Comment by moritzmhmk** [comment]
shouldn't it be `homebridge-camera-rpi` instead of `homebridge-rpi-camera`?

**Comment by donavanbecker** [comment]
> shouldn't it be `homebridge-camera-rpi` instead of `homebridge-rpi-camera`?

Yes sorry!

**Comment by moritzmhmk** [comment]
I updated the identifier. When you confirm that it works I will merge. I can't test this myself currently.

**Comment by donavanbecker** [comment]
should be good to go! no more warning log. Thanks

**Comment by moritzmhmk** [comment]
v0.0.6 released - thanks!

**Pull request merged**
