### PR TITLE
Adds random SSRC to ensure multiple cameras work at once

### PR DESCRIPTION
**Pull request by aaronpearce**
Per the HAP changes, KhaosT/HAP-NodeJS#558

This will allow you to connect to multiple cameras at once when live.

### CODE REVIEW

**Comment by KhaosT** [comment]
Make sure you generate it as `Int32` instead of `UInt32` otherwise ffmpeg will not be happy about that.
```
let ssrcSource = crypto.randomBytes(4);
ssrcSource[0] = 0;
let ssrc = ssrcSource.readInt32BE(0, true);
```

**Comment by aaronpearce** [comment]
Will update my PR here

**Comment by moritzmhmk** [comment]
Thanks for the pull request.

Please adjust your code to follow [JavaScript Standard Style](https://standardjs.com/). 

What exactly do you mean by "connect to multiple cameras at once when live"? I thought one Apple device could only open one camera at a time in live view anyway?

**Comment by aaronpearce** [comment]
Will update with the code style fixes today.

Third party apps like the one I have made, Homecam for HomeKit, allow a single device to view multiple cameras at once live.

**Comment by wildbomb** [comment]
`var crypto = require('crypto');`
is missing in this PR

**Comment by aaronpearce** [comment]
Should be fixed to standard now. 

As a note, there are other issues pointed out by the Standard linter, which I did not fix as they were unrelated to this change.

**Comment by moritzmhmk** [comment]
I will raise the version number and publish on npm as soon as I can test it

**Pull request merged**
